apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-secrets
  namespace: nexus
  labels:
    app.kubernetes.io/name: nexus-secrets
    app.kubernetes.io/part-of: nexus-lead-intelligence
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nexus-azure-keyvault
  target:
    name: nexus-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: nexus-prod-STRIPE-SECRET-KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: nexus-prod-STRIPE-WEBHOOK-SECRET
    - secretKey: PRICE_ID
      remoteRef:
        key: nexus-prod-PRICE-ID
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexus-prod-DATABASE-URL
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: nexus-prod-RESEND-API-KEY
    - secretKey: RESEND_FROM
      remoteRef:
        key: nexus-prod-RESEND-FROM
    - secretKey: WAITLIST_NOTIFY_TO
      remoteRef:
        key: nexus-prod-WAITLIST-NOTIFY-TO
    - secretKey: HUBSPOT_ACCESS_TOKEN
      remoteRef:
        key: nexus-prod-HUBSPOT-ACCESS-TOKEN
    - secretKey: HUBSPOT_PORTAL_ID
      remoteRef:
        key: nexus-prod-HUBSPOT-PORTAL-ID
