apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: nexus-azure-keyvault
  labels:
    app.kubernetes.io/name: nexus-azure-keyvault
    app.kubernetes.io/part-of: nexus-platform
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      tenantId: 2a9e4c0a-7d39-4898-945c-43628ebb4f54
      vaultUrl: https://nexusvault28095.vault.azure.net
      serviceAccountRef:
        name: nexus-external-secrets
        namespace: nexus
