apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-keyvault-smoke
  namespace: nexus
  labels:
    app.kubernetes.io/name: nexus-keyvault-smoke
    app.kubernetes.io/part-of: nexus-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nexus-azure-keyvault
  target:
    name: nexus-keyvault-smoke
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DB-URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
