apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-secrets
  namespace: nexus
  labels:
    app.kubernetes.io/name: nexus-secrets
    app.kubernetes.io/part-of: nexus-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nexus-azure-keyvault
  target:
    name: nexus-secrets
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: nexus-prod-DATABASE-URL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HUBSPOT_ACCESS_TOKEN
      remoteRef:
        key: nexus-prod-HUBSPOT-ACCESS-TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HUBSPOT_PORTAL_ID
      remoteRef:
        key: nexus-prod-HUBSPOT-PORTAL-ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: JWT_SECRET
      remoteRef:
        key: nexus-prod-JWT-SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: PRICE_ID
      remoteRef:
        key: nexus-prod-PRICE-ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: nexus-prod-RESEND-API-KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: RESEND_FROM
      remoteRef:
        key: nexus-prod-RESEND-FROM
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: nexus-prod-STRIPE-SECRET-KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteRef:
        key: nexus-prod-STRIPE-WEBHOOK-SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WAITLIST_NOTIFY_TO
      remoteRef:
        key: nexus-prod-WAITLIST-NOTIFY-TO
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
