apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-external-secrets
  namespace: nexus
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: nexus-external-secrets
    app.kubernetes.io/part-of: nexus-platform
  annotations:
    azure.workload.identity/client-id: 43acaa30-8346-481f-924e-126abcda6f4d
    azure.workload.identity/tenant-id: 2a9e4c0a-7d39-4898-945c-43628ebb4f54
