replicaCount: 3

image:
  tag: latest

env:
  PUBLIC_BASE_URL: "https://nexuscloud.sh"
  TRACKING_ALLOWED_ORIGIN: "https://nexuscloud.sh"
  ENVIRONMENT: "production"

ingress:
  enabled: true
  className: nginx
  backendServiceName: nexus-backend
  backendServicePort: 8000
  hosts:
    - host: nexuscloud.sh
      paths:
        - path: /hubspot
          pathType: Prefix
        - path: /api
          pathType: Prefix
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: "2"
    memory: 2Gi
