apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexus
resources:
  - namespaces/nexus-namespace.yaml
  - deployments/nexus-api-deployment.yaml
  - deployments/nexus-worker-deployment.yaml
  - cronjobs/nexus-scraper-quality-cronjob.yaml
  - cronjobs/nexus-internal-health-cronjob.yaml
  - services/nexus-api-service.yaml
  - services/nexus-backend-service.yaml
  - ingress/nexus-ingress.yaml

images:
  - name: crjqmupr2v7hmzm.azurecr.io/nexus-api
    newTag: latest
  - name: crjqmupr2v7hmzm.azurecr.io/nexus-worker
    newTag: latest
