apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "nexus.fullname" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
